Repository Exawind/openturbine, pull requests merged in 2024-07, with the labels that each got.

#196 Add rigid constraints between nodes, create Model struct for managing nodes and constraints
  src/restruct_poc/beams/beam_node.hpp
  src/restruct_poc/beams/create_beams.hpp
  src/restruct_poc/beams/populate_element_views.hpp
  src/restruct_poc/model/model.hpp
  src/restruct_poc/model/node.hpp
  src/restruct_poc/solver/assemble_constraints.hpp
  src/restruct_poc/solver/calculate_constraint_X0.hpp
  src/restruct_poc/solver/calculate_constraint_residual_gradient.hpp
  src/restruct_poc/solver/constraint.hpp
  src/restruct_poc/solver/constraint_input.hpp
  src/restruct_poc/solver/constraints.hpp
  src/restruct_poc/solver/initialize_constraints.hpp
  src/restruct_poc/solver/populate_sparse_indices_constraints.hpp
  src/restruct_poc/solver/populate_sparse_indices_constraints_transpose.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs_constraints.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs_constraints_transpose.hpp
  src/restruct_poc/solver/populate_tangent_indices.hpp
  src/restruct_poc/solver/populate_tangent_row_ptrs.hpp
  src/restruct_poc/solver/solver.hpp
  src/restruct_poc/solver/state.hpp
  src/restruct_poc/types.hpp
  tests/unit_tests/restruct_poc/test_beams.cpp
  tests/unit_tests/restruct_poc/test_cantilever_beam.cpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
  tests/unit_tests/restruct_poc/test_solver.cpp
  tests/unit_tests/restruct_poc/vtkout.hpp
Labels: enhancement

#202 Add Rotation Control Constraint and Turbine Controller. Couple IEA15 rotor to controller to demonstrate blade pitching
  CMakeLists.txt
  src/restruct_poc/math/quaternion_operations.hpp
  src/restruct_poc/model/model.hpp
  src/restruct_poc/solver/assemble_constraints.hpp
  src/restruct_poc/solver/calculate_constraint_residual_gradient.hpp
  src/restruct_poc/solver/constraint.hpp
  src/restruct_poc/solver/constraints.hpp
  src/restruct_poc/solver/populate_sparse_indices_constraints.hpp
  src/restruct_poc/solver/populate_sparse_indices_constraints_transpose.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs_constraints.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs_constraints_transpose.hpp
  src/restruct_poc/solver/solver.hpp
  src/restruct_poc/solver/state.hpp
  src/restruct_poc/solver/update_state_prediction.hpp
  src/restruct_poc/types.hpp
  src/utilities/CMakeLists.txt
  src/utilities/controllers/controller_io.hpp
  src/utilities/controllers/discon.cpp
  src/utilities/controllers/discon.h
  src/utilities/controllers/discon.hpp
  src/utilities/controllers/discon_rotor_test_controller.cpp
  src/utilities/controllers/discon_rotor_test_controller.hpp
  src/utilities/controllers/turbine_controller.cpp
  src/utilities/controllers/turbine_controller.hpp
  tests/unit_tests/restruct_poc/iea15_rotor_data.hpp
  tests/unit_tests/restruct_poc/test_controller.cpp
  tests/unit_tests/restruct_poc/test_math.cpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
  tests/unit_tests/restruct_poc/vtkout.hpp
Labels: enhancement

#207 Add Cylindrical Constraint
  src/restruct_poc/math/vector_operations.hpp
  src/restruct_poc/model/model.hpp
  src/restruct_poc/solver/calculate_constraint_residual_gradient.hpp
  src/restruct_poc/solver/compute_number_of_non_zeros_constraints.hpp
  src/restruct_poc/solver/constraint.hpp
  src/restruct_poc/solver/populate_sparse_indices_constraints.hpp
  src/restruct_poc/solver/populate_sparse_indices_constraints_transpose.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs_col_inds_constraints.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs_col_inds_transpose.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs_constraints.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs_constraints_transpose.hpp
  src/restruct_poc/solver/solver.hpp
  tests/unit_tests/restruct_poc/test_math.cpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_utilities.cpp
  tests/unit_tests/restruct_poc/test_utilities.hpp
  tests/unit_tests/restruct_poc/vtkout.hpp
Labels: enhancement

#218 Fixed failing test on GPU
  tests/unit_tests/restruct_poc/test_math.cpp
Labels: bug

#199 Convert windIO schema -> C++ structs
  src/utilities/scripts/IEAontology_schema.yaml
  src/utilities/scripts/windio.py
  src/utilities/scripts/windio_mapped_structs.cpp
Labels: enhancement, IO
