Repository Exawind/openturbine, pull requests merged in 2024-09, with the labels that each got.

#257 Changed the formatting CI workflow to no longer need the DoozyX action
  .github/workflows/formatting.yaml
  src/vendor/dylib/dylib.hpp
Labels: ci/cd

#250 Moved data structures in Beams from node-based to per-element-per-node based
  src/restruct_poc/beams/beams.hpp
  src/restruct_poc/beams/calculate_jacobian.hpp
  src/restruct_poc/beams/create_beams.hpp
  src/restruct_poc/beams/interpolate_QP_position.hpp
  src/restruct_poc/beams/interpolate_QP_rotation.hpp
  src/restruct_poc/beams/interpolate_QP_rotation_derivative.hpp
  src/restruct_poc/beams/interpolate_QP_state.hpp
  src/restruct_poc/beams/interpolate_QP_vector.hpp
  src/restruct_poc/beams/interpolate_to_quadrature_points.hpp
  src/restruct_poc/beams/interpolation_operations.hpp
  src/restruct_poc/beams/set_node_state_indices.hpp
  src/restruct_poc/model/model.hpp
  src/restruct_poc/solver/populate_sparse_indices.hpp
  src/restruct_poc/system/assemble_residual_vector.hpp
  src/restruct_poc/system/calculate_node_forces.hpp
  src/restruct_poc/system/integrate_residual_vector.hpp
  src/restruct_poc/system/update_node_state.hpp
  src/restruct_poc/system/update_state.hpp
  tests/unit_tests/restruct_poc/beams/test_interpolate_QP_state.cpp
  tests/unit_tests/restruct_poc/beams/test_interpolate_QP_vector.cpp
  tests/unit_tests/restruct_poc/solver/test_populate_sparse_indices.cpp
  tests/unit_tests/restruct_poc/system/test_calculate_node_forces.cpp
  tests/unit_tests/restruct_poc/system/test_integrate_matrix.hpp
  tests/unit_tests/restruct_poc/system/test_integrate_residual_vector.cpp
  tests/unit_tests/restruct_poc/system/test_update_node_state.cpp
  tests/unit_tests/restruct_poc/test_beams.cpp
  tests/unit_tests/restruct_poc/test_cantilever_beam.cpp
  tests/unit_tests/restruct_poc/test_utilities.cpp
  tests/unit_tests/restruct_poc/test_utilities.hpp
Labels: code-refactoring

#251 Removed ElemIndices data structure with two Views of size_t
  src/restruct_poc/beams/beams.hpp
  src/restruct_poc/beams/calculate_jacobian.hpp
  src/restruct_poc/beams/create_beams.hpp
  src/restruct_poc/beams/interpolate_QP_position.hpp
  src/restruct_poc/beams/interpolate_QP_rotation.hpp
  src/restruct_poc/beams/interpolate_QP_state.hpp
  src/restruct_poc/beams/interpolate_QP_vector.hpp
  src/restruct_poc/beams/interpolate_to_quadrature_points.hpp
  src/restruct_poc/solver/compute_number_of_non_zeros.hpp
  src/restruct_poc/solver/populate_sparse_indices.hpp
  src/restruct_poc/solver/populate_sparse_row_ptrs.hpp
  src/restruct_poc/solver/solver.hpp
  src/restruct_poc/system/assemble_inertia_matrix.hpp
  src/restruct_poc/system/assemble_residual_vector.hpp
  src/restruct_poc/system/assemble_stiffness_matrix.hpp
  src/restruct_poc/system/calculate_node_forces.hpp
  src/restruct_poc/system/calculate_quadrature_point_values.hpp
  src/restruct_poc/system/integrate_inertia_matrix.hpp
  src/restruct_poc/system/integrate_residual_vector.hpp
  src/restruct_poc/system/integrate_stiffness_matrix.hpp
  src/restruct_poc/system/update_node_state.hpp
  src/restruct_poc/system/update_state.hpp
  tests/unit_tests/restruct_poc/beams/test_interpolate_QP_state.cpp
  tests/unit_tests/restruct_poc/beams/test_interpolate_QP_vector.cpp
  tests/unit_tests/restruct_poc/solver/test_compute_number_of_non_zeros.cpp
  tests/unit_tests/restruct_poc/solver/test_populate_sparse_indices.cpp
  tests/unit_tests/restruct_poc/solver/test_populate_sparse_row_ptrs.cpp
  tests/unit_tests/restruct_poc/system/test_calculate_node_forces.cpp
  tests/unit_tests/restruct_poc/system/test_integrate_inertia_matrix.cpp
  tests/unit_tests/restruct_poc/system/test_integrate_stiffness_matrix.cpp
Labels: code-refactoring

#253 Add generator torque to the azimuth DOF
  src/constraints/calculate_constraint_force.hpp
  src/constraints/calculate_constraint_residual_gradient.hpp
  src/constraints/calculate_revolute_joint_constraint.hpp
  src/constraints/calculate_revolute_joint_force.hpp
  src/constraints/calculate_rigid_joint_constraint.hpp
  src/constraints/constraint.hpp
  src/constraints/constraint_type.hpp
  src/constraints/constraints.hpp
  src/math/vector_operations.hpp
  src/model/model.hpp
  src/solver/contribute_constraints_system_residual_to_vector.hpp
  src/step/assemble_constraints_residual.hpp
  src/step/update_constraint_variables.hpp
  src/types.hpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/regression/test_rotating_beam.cpp
  tests/unit_tests/regression/test_rotor.cpp
  tests/unit_tests/regression/test_utilities.cpp
  tests/unit_tests/regression/test_utilities.hpp
  tests/unit_tests/regression/vtkout.hpp
  tests/unit_tests/solver/test_compute_number_of_non_zeros_constraints.cpp
  tests/unit_tests/solver/test_populate_sparse_row_ptrs_col_inds_constraints.cpp
Labels: enhancement, code-refactoring

#272 Calculate current node and quadrature point position
  src/beams/beams.hpp
  src/beams/calculate_QP_deformation.hpp
  src/beams/calculate_QP_position.hpp
  src/beams/create_beams.hpp
  src/beams/interpolate_to_quadrature_points.hpp
  src/model/model.hpp
  src/state/copy_nodes_to_state.hpp
  src/state/state.hpp
  src/state/update_global_position.hpp
  src/step/step.hpp
  src/step/update_system_variables.hpp
  src/system/calculate_RR0.hpp
  src/system/calculate_quadrature_point_values.hpp
  tests/unit_tests/model/test_model.cpp
  tests/unit_tests/regression/test_beams.cpp
  tests/unit_tests/regression/test_cantilever_beam.cpp
  tests/unit_tests/regression/test_rotating_beam.cpp
  tests/unit_tests/regression/test_rotor.cpp
  tests/unit_tests/regression/test_solver.cpp
  tests/unit_tests/regression/vtkout.hpp
  tests/unit_tests/system/test_calculate_RR0.cpp
Labels: enhancement

#273 Add option to build ROSCO as an external project
  .github/workflows/correctness-linux.yaml
  .github/workflows/correctness-macos.yaml
  cmake/Dependencies.cmake
  cmake/OpenTurbineOptions.cmake
  src/constraints/calculate_constraint_force.hpp
  src/constraints/calculate_constraint_output.hpp
  src/constraints/calculate_constraint_residual_gradient.hpp
  src/constraints/calculate_fixed_bc_constraint.hpp
  src/constraints/calculate_prescribed_bc_constraint.hpp
  src/constraints/calculate_revolute_joint_constraint.hpp
  src/constraints/calculate_revolute_joint_force.hpp
  src/constraints/calculate_rigid_joint_constraint.hpp
  src/constraints/calculate_rotation_control_constraint.hpp
  src/constraints/constraints.hpp
  src/math/quaternion_operations.hpp
  src/step/step.hpp
  src/step/update_constraint_variables.hpp
  src/utilities/controllers/controller_io.hpp
  src/utilities/controllers/discon.cpp
  src/utilities/controllers/discon_rotor_test_controller.cpp
  tests/unit_tests/external/CMakeLists.txt
  tests/unit_tests/external/test_rosco_controller.cpp
  tests/unit_tests/regression/test_controller.cpp
  tests/unit_tests/regression/test_math.cpp
  tests/unit_tests/regression/test_rotating_beam.cpp
  tests/unit_tests/regression/test_rotor.cpp
Labels: enhancement, cmake
