Repository Exawind/openturbine, pull requests merged in 2024-08, with the labels that each got.

#217 Refactor Model class to hold smart pointers as its attributes
  src/restruct_poc/model/model.hpp
  src/restruct_poc/model/node.hpp
  src/restruct_poc/solver/constraints.hpp
  src/restruct_poc/solver/solver.hpp
  src/restruct_poc/solver/state.hpp
  tests/unit_tests/restruct_poc/CMakeLists.txt
  tests/unit_tests/restruct_poc/model/test_model.cpp
  tests/unit_tests/restruct_poc/test_beams.cpp
  tests/unit_tests/restruct_poc/test_cantilever_beam.cpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
  tests/unit_tests/restruct_poc/test_solver.cpp
Labels: code-refactoring

#197 Parse a windIO yaml input file and instantiate the turbine structs
  .github/workflows/clang-tidy.yaml
  .github/workflows/correctness-linux.yaml
  .github/workflows/correctness-macos.yaml
  .github/workflows/cppcheck.yaml
  Dependencies.cmake
  src/CMakeLists.txt
  src/utilities/controllers/discon_rotor_test_controller.cpp
  src/utilities/controllers/turbine_controller.cpp
  src/utilities/scripts/IEA-15-240-RWT.yaml
  src/utilities/scripts/windio.py
  src/utilities/scripts/windio_mapped_structs.cpp
  src/utilities/scripts/windio_mapped_structs.hpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/restruct_poc/CMakeLists.txt
  tests/unit_tests/restruct_poc/test_cantilever_beam.cpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
  tests/unit_tests/restruct_poc/test_yaml_parser.cpp
Labels: enhancement

#241 Implemented SIMD loop for second node loop in integration.
  src/restruct_poc/system/integrate_inertia_matrix.hpp
  src/restruct_poc/system/integrate_stiffness_matrix.hpp
  tests/unit_tests/restruct_poc/system/test_integrate_inertia_matrix.cpp
  tests/unit_tests/restruct_poc/system/test_integrate_matrix.hpp
  tests/unit_tests/restruct_poc/system/test_integrate_stiffness_matrix.cpp
Labels: code-efficiency, code-refactoring
