Repository Exawind/openturbine, pull requests merged in 2024-04, with the labels that each got.

#129 Restructuring proof-of-concept
  .github/workflows/ci.yaml
  CMakeLists.txt
  src/CMakeLists.txt
  src/gebt_poc/dynamic_beam_element.h
  src/gebt_poc/linear_solver.h
  src/gebt_poc/static_beam_element.h
  src/gen_alpha_poc/quaternion.h
  src/gen_alpha_poc/vector.h
  src/restruct_poc/CMakeLists.txt
  src/restruct_poc/beams.hpp
  src/restruct_poc/beams_data.hpp
  src/restruct_poc/beams_functors.hpp
  src/restruct_poc/beams_input.cpp
  src/restruct_poc/beams_input.hpp
  src/restruct_poc/beams_methods.cpp
  src/restruct_poc/beams_methods.hpp
  src/restruct_poc/dynamic_beam.cpp
  src/restruct_poc/solver.cpp
  src/restruct_poc/solver.hpp
  src/restruct_poc/solver_functors.hpp
  src/restruct_poc/state.hpp
  src/restruct_poc/types.hpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/gen_alpha_poc/test_utilities.cpp
  tests/unit_tests/gen_alpha_poc/test_utilities.h
  tests/unit_tests/restruct_poc/CMakeLists.txt
  tests/unit_tests/restruct_poc/test_beams.cpp
  tests/unit_tests/restruct_poc/test_cantilever_beam.cpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
  tests/unit_tests/restruct_poc/test_solver.cpp
  tests/unit_tests/restruct_poc/vtkout.hpp
Labels: code-efficiency

#146 Fixes CPU performance regression from latest GPU optimization.
  src/restruct_poc/AssembleElasticStiffnessMatrix.hpp
  src/restruct_poc/AssembleGyroscopicInertiaMatrix.hpp
  src/restruct_poc/AssembleInertialStiffnessMatrix.hpp
  src/restruct_poc/AssembleMassMatrix.hpp
  src/restruct_poc/IntegrateMatrix.hpp
Labels: bug, code-efficiency

#147 Replace hand rolled BLAS with Kokkos-Kernels on Device
  src/restruct_poc/AssembleElasticStiffnessMatrix.hpp
  src/restruct_poc/AssembleGyroscopicInertiaMatrix.hpp
  src/restruct_poc/AssembleInertialStiffnessMatrix.hpp
  src/restruct_poc/AssembleMassMatrix.hpp
  src/restruct_poc/CalculateCuu.hpp
  src/restruct_poc/CalculateForceFC.hpp
  src/restruct_poc/CalculateForceFD.hpp
  src/restruct_poc/CalculateGravityForce.hpp
  src/restruct_poc/CalculateGyroscopicMatrix.hpp
  src/restruct_poc/CalculateInertiaStiffnessMatrix.hpp
  src/restruct_poc/CalculateInertialForces.hpp
  src/restruct_poc/CalculateMuu.hpp
  src/restruct_poc/CalculateOuu.hpp
  src/restruct_poc/CalculatePuu.hpp
  src/restruct_poc/CalculateQuu.hpp
  src/restruct_poc/CalculateStrain.hpp
  src/restruct_poc/CalculateTangentOperator.hpp
  src/restruct_poc/IntegrateMatrix.hpp
  src/restruct_poc/MatrixOperations.hpp
  src/restruct_poc/UpdateState.hpp
  src/restruct_poc/VectorOperations.hpp
  src/restruct_poc/beams.hpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
Labels: code-quality, code-efficiency
