Repository Exawind/openturbine, pull requests merged in 2024-05, with the labels that each got.

#148 Remove Quaternion and Vector Usage
  src/restruct_poc/AssembleElasticStiffnessMatrix.hpp
  src/restruct_poc/AssembleGyroscopicInertiaMatrix.hpp
  src/restruct_poc/AssembleInertialStiffnessMatrix.hpp
  src/restruct_poc/AssembleMassMatrix.hpp
  src/restruct_poc/BeamNode.hpp
  src/restruct_poc/CalculateCuu.hpp
  src/restruct_poc/CalculateForceFC.hpp
  src/restruct_poc/CalculateForceFD.hpp
  src/restruct_poc/CalculateGravityForce.hpp
  src/restruct_poc/CalculateGyroscopicMatrix.hpp
  src/restruct_poc/CalculateInertiaStiffnessMatrix.hpp
  src/restruct_poc/CalculateInertialForces.hpp
  src/restruct_poc/CalculateMuu.hpp
  src/restruct_poc/CalculateOuu.hpp
  src/restruct_poc/CalculatePuu.hpp
  src/restruct_poc/CalculateQuu.hpp
  src/restruct_poc/CalculateRR0.hpp
  src/restruct_poc/CalculateStrain.hpp
  src/restruct_poc/CalculateTangentOperator.hpp
  src/restruct_poc/CalculateTemporaryVariables.hpp
  src/restruct_poc/IntegrateMatrix.hpp
  src/restruct_poc/MatrixOperations.hpp
  src/restruct_poc/QuaternionOperations.hpp
  src/restruct_poc/UpdateState.hpp
  src/restruct_poc/VectorOperations.hpp
  src/restruct_poc/beams.hpp
  src/restruct_poc/solver/CalculateConstraintResidualGradient.hpp
  src/restruct_poc/solver/CalculateDisplacement.hpp
  src/restruct_poc/types.hpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
  tests/unit_tests/restruct_poc/test_solver.cpp
Labels: code-quality

#151 Optimize and Consolidate Code a Little
  src/restruct_poc/CalculateCuu.hpp
  src/restruct_poc/CalculateMuu.hpp
  src/restruct_poc/CalculateNodeForces.hpp
  src/restruct_poc/RotateSectionMatrix.hpp
  src/restruct_poc/UpdateState.hpp
  src/restruct_poc/solver/AssembleSystem.hpp
  src/restruct_poc/solver/SolveSystem.hpp
  tests/unit_tests/restruct_poc/test_solver.cpp
Labels: code-quality, code-efficiency

#158 Fixes CI environment on MacOS
  .github/workflows/ci.yaml
Labels: bug, ci/cd

#165 Clang-Format to allow that line to pass on CI
  src/restruct_poc/beams/create_beams.hpp
  src/restruct_poc/solver/calculate_constraint_residual_gradient.hpp
  src/restruct_poc/solver/calculate_displacement.hpp
  src/restruct_poc/system/assemble_elastic_stiffness_matrix.hpp
  src/restruct_poc/system/assemble_gyroscopic_inertia_matrix.hpp
  src/restruct_poc/system/assemble_inertial_stiffness_matrix.hpp
  src/restruct_poc/system/assemble_mass_matrix.hpp
  src/restruct_poc/system/assemble_residual_vector.hpp
  src/restruct_poc/system/calculate_strain.hpp
  src/restruct_poc/system/calculate_temporary_variables.hpp
  src/restruct_poc/system/update_state.hpp
  tests/unit_tests/restruct_poc/test_beams.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
Labels: bug, ci/cd, code-quality

#160 Remove trailing underscores from functions arguments of restruct_poc
  src/restruct_poc/beams/beam_element.hpp
  src/restruct_poc/beams/beam_node.hpp
  src/restruct_poc/beams/beam_section.hpp
  src/restruct_poc/beams/beams.hpp
  src/restruct_poc/beams/beams_input.hpp
  src/restruct_poc/beams/calculate_jacobian.hpp
  src/restruct_poc/beams/interpolate_QP_acceleration.hpp
  src/restruct_poc/beams/interpolate_QP_position.hpp
  src/restruct_poc/beams/interpolate_QP_rotation.hpp
  src/restruct_poc/beams/interpolate_QP_rotation_derivative.hpp
  src/restruct_poc/beams/interpolate_QP_state.hpp
  src/restruct_poc/beams/interpolate_QP_velocity.hpp
  src/restruct_poc/beams/populate_element_views.hpp
Labels: code-quality

#162 Tweak static analysis tool settings to improve their usefulness
  .clang-tidy
  .github/workflows/ci.yaml
  src/CMakeLists.txt
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/restruct_poc/CMakeLists.txt
  tests/unit_tests/restruct_poc/test_beams.cpp
  tests/unit_tests/restruct_poc/test_cantilever_beam.cpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
  tests/unit_tests/restruct_poc/test_solver.cpp
  tests/unit_tests/restruct_poc/test_utilities.cpp
  tests/unit_tests/restruct_poc/test_utilities.hpp
Labels: ci/cd

#163 Unit tests for math functions in restruct_poc
  src/restruct_poc/math/quaternion_operations.hpp
  src/restruct_poc/math/vector_operations.hpp
  src/restruct_poc/solver/calculate_constraint_residual_gradient.hpp
  src/restruct_poc/system/calculate_strain.hpp
  src/restruct_poc/types.hpp
  tests/unit_tests/restruct_poc/CMakeLists.txt
  tests/unit_tests/restruct_poc/test_beams.cpp
  tests/unit_tests/restruct_poc/test_cantilever_beam.cpp
  tests/unit_tests/restruct_poc/test_math.cpp
  tests/unit_tests/restruct_poc/test_rotating_beam.cpp
  tests/unit_tests/restruct_poc/test_rotor.cpp
  tests/unit_tests/restruct_poc/test_solver.cpp
  tests/unit_tests/restruct_poc/test_utilities.cpp
  tests/unit_tests/restruct_poc/test_utilities.hpp
Labels: testing

#168 Added a series of unit tests to cover the IntegrateMatrix kernels
  tests/unit_tests/restruct_poc/CMakeLists.txt
  tests/unit_tests/restruct_poc/system/test_integrate_matrix.cpp
Labels: testing

#169 Add integrate elastic stiffness matrix tests
  tests/unit_tests/restruct_poc/CMakeLists.txt
  tests/unit_tests/restruct_poc/system/test_integrate_elastic_stiffness_matrix.cpp
  tests/unit_tests/restruct_poc/system/test_integrate_matrix.cpp
  tests/unit_tests/restruct_poc/system/test_integrate_matrix.hpp
Labels: testing
