Repository Exawind/openturbine, pull requests merged in 2025-01, with the labels that each got.

#323 Create finite element assembly for Springs elements
  src/dof_management/assemble_node_freedom_allocation_table.hpp
  src/dof_management/create_element_freedom_table.hpp
  src/elements/elements.hpp
  src/elements/springs/spring_element.hpp
  src/elements/springs/springs.hpp
  src/solver/contribute_beams_to_sparse_matrix.hpp
  src/solver/contribute_beams_to_vector.hpp
  src/solver/contribute_masses_to_sparse_matrix.hpp
  src/solver/contribute_masses_to_vector.hpp
  src/solver/contribute_springs_to_sparse_matrix.hpp
  src/solver/contribute_springs_to_vector.hpp
  src/step/assemble_residual_vector_springs.hpp
  src/step/assemble_stiffness_matrix_springs.hpp
  src/step/assemble_system_matrix.hpp
  src/step/assemble_system_residual.hpp
  src/step/update_system_variables.hpp
  src/step/update_system_variables_masses.hpp
  src/step/update_system_variables_springs.hpp
  src/system/springs/calculate_distance_components.hpp
  src/system/springs/calculate_force_coefficients.hpp
  src/system/springs/calculate_force_vectors.hpp
  src/system/springs/calculate_length.hpp
  src/system/springs/calculate_stiffness_matrix.hpp
  src/system/springs/update_node_state.hpp
  tests/regression_tests/external/test_rotor_aero_controller.cpp
  tests/regression_tests/regression/CMakeLists.txt
  tests/regression_tests/regression/test_cantilever_beam.cpp
  tests/regression_tests/regression/test_precession.cpp
  tests/regression_tests/regression/test_rotating_beam.cpp
  tests/regression_tests/regression/test_rotor.cpp
  tests/regression_tests/regression/test_solver.cpp
  tests/regression_tests/regression/test_spring_mass_system.cpp
  tests/regression_tests/regression/test_springs.cpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/dof_management/test_assemble_node_freedom_allocation_table.cpp
  tests/unit_tests/dof_management/test_create_element_freedom_table.cpp
  tests/unit_tests/elements/springs/test_spring_element.cpp
  tests/unit_tests/elements/springs/test_springs_input.cpp
  tests/unit_tests/elements/test_elements.cpp
  tests/unit_tests/step/CMakeLists.txt
  tests/unit_tests/step/test_assemble_residual_vector_springs.cpp
  tests/unit_tests/step/test_assemble_stiffness_matrix_springs.cpp
  tests/unit_tests/system/springs/CMakeLists.txt
  tests/unit_tests/system/springs/test_calculate_distance_components.cpp
  tests/unit_tests/system/springs/test_calculate_force_coefficients.cpp
  tests/unit_tests/system/springs/test_calculate_force_vectors.cpp
  tests/unit_tests/system/springs/test_calculate_length.cpp
  tests/unit_tests/system/springs/test_calculate_stiffness_matrix.cpp
  tests/unit_tests/system/springs/test_update_node_state.cpp
Labels: enhancement

#328 Revise model class to remove shared pointers, add spring elements, and simplify component construction
  cmake/Dependencies.cmake
  src/constraints/constraint.hpp
  src/constraints/constraints.hpp
  src/elements/beams/beam_element.hpp
  src/elements/beams/beam_node.hpp
  src/elements/beams/beams_input.hpp
  src/elements/beams/create_beams.hpp
  src/elements/beams/populate_element_views.hpp
  src/elements/masses/create_masses.hpp
  src/elements/masses/mass_element.hpp
  src/elements/springs/create_springs.hpp
  src/elements/springs/spring_element.hpp
  src/model/copy_nodes_to_state.hpp
  src/model/model.hpp
  src/model/node.hpp
  tests/regression_tests/external/test_rotor_aero_controller.cpp
  tests/regression_tests/regression/test_beams.cpp
  tests/regression_tests/regression/test_cantilever_beam.cpp
  tests/regression_tests/regression/test_masses.cpp
  tests/regression_tests/regression/test_precession.cpp
  tests/regression_tests/regression/test_rotating_beam.cpp
  tests/regression_tests/regression/test_rotor.cpp
  tests/regression_tests/regression/test_solver.cpp
  tests/regression_tests/regression/test_spring_mass_system.cpp
  tests/regression_tests/regression/test_springs.cpp
  tests/unit_tests/dof_management/test_assemble_node_freedom_allocation_table.cpp
  tests/unit_tests/elements/beams/test_beams_input.cpp
  tests/unit_tests/elements/masses/test_masses_input.cpp
  tests/unit_tests/elements/springs/test_spring_element.cpp
  tests/unit_tests/elements/springs/test_springs_input.cpp
  tests/unit_tests/model/test_copy_nodes_to_state.cpp
  tests/unit_tests/model/test_model.cpp
  tests/unit_tests/step/test_assemble_residual_vector_springs.cpp
  tests/unit_tests/step/test_assemble_stiffness_matrix_springs.cpp
Labels: enhancement, code-refactoring

#330 Fixed Spring-Mass chain regression test to use new model constructor methods
  tests/regression_tests/regression/test_spring_mass_system.cpp
Labels: bug

#333 Initial CFD Interface Implementation
  src/CMakeLists.txt
  src/elements/masses/masses.hpp
  src/elements/springs/springs.hpp
  src/elements/springs/springs_input.hpp
  src/interfaces/cfd/CMakeLists.txt
  src/interfaces/cfd/floating_platform.hpp
  src/interfaces/cfd/floating_platform_input.hpp
  src/interfaces/cfd/interface.cpp
  src/interfaces/cfd/interface.hpp
  src/interfaces/cfd/interface_input.hpp
  src/interfaces/cfd/mooring_line.hpp
  src/interfaces/cfd/mooring_line_input.hpp
  src/interfaces/cfd/node_data.hpp
  src/interfaces/cfd/turbine.hpp
  src/interfaces/cfd/turbine_input.hpp
  src/model/model.hpp
  src/solver/contribute_forces_to_vector.hpp
  src/state/clone_state.hpp
  src/state/copy_state_data.hpp
  src/state/set_node_external_loads.hpp
  src/state/state.hpp
  src/step/assemble_system_residual.hpp
  src/step/step.hpp
  tests/regression_tests/CMakeLists.txt
  tests/regression_tests/interfaces/CMakeLists.txt
  tests/regression_tests/interfaces/test_cfd_interface.cpp
  tests/regression_tests/regression/test_masses.cpp
  tests/regression_tests/regression/test_solver.cpp
Labels: enhancement

#334 Suppresses CppCheck warning about missing member copy.
  src/solver/solver.hpp
Labels: bug

#327 Enable definition of constraints from a 6-DOF (base) node to a 3-DOF (target) node
  src/constraints/calculate_constraint_force.hpp
  src/constraints/calculate_constraint_output.hpp
  src/constraints/calculate_constraint_residual_gradient.hpp
  src/constraints/calculate_fixed_bc_constraint.hpp
  src/constraints/calculate_prescribed_bc_constraint.hpp
  src/constraints/calculate_revolute_joint_constraint.hpp
  src/constraints/calculate_revolute_joint_force.hpp
  src/constraints/calculate_revolute_joint_output.hpp
  src/constraints/calculate_rigid_joint_constraint.hpp
  src/constraints/calculate_rotation_control_constraint.hpp
  src/constraints/constraint.hpp
  src/constraints/constraint_type.hpp
  src/constraints/constraints.hpp
  src/constraints/update_lambda_prediction.hpp
  src/dof_management/assemble_node_freedom_allocation_table.hpp
  src/dof_management/create_constraint_freedom_table.hpp
  src/dof_management/freedom_signature.hpp
  src/elements/elements.hpp
  src/model/copy_nodes_to_state.hpp
  src/model/model.hpp
  src/model/node.hpp
  src/solver/calculate_error_sum_squares.hpp
  src/solver/compute_b_num_non_zero.hpp
  src/solver/compute_number_of_non_zeros_constraints.hpp
  src/solver/create_b_matrix.hpp
  src/solver/create_b_t_matrix.hpp
  src/solver/populate_sparse_row_ptrs_col_inds_constraints.hpp
  src/solver/solver.hpp
  src/step/assemble_constraints_matrix.hpp
  src/step/assemble_constraints_residual.hpp
  src/step/calculate_convergence_error.hpp
  src/step/step.hpp
  src/step/step_parameters.hpp
  src/step/update_constraint_prediction.hpp
  src/step/update_constraint_variables.hpp
  tests/regression_tests/external/test_rotor_aero_controller.cpp
  tests/regression_tests/regression/CMakeLists.txt
  tests/regression_tests/regression/test_heavy_top.cpp
  tests/regression_tests/regression/test_rotating_beam.cpp
  tests/regression_tests/regression/test_rotor.cpp
  tests/regression_tests/regression/test_solver.cpp
  tests/regression_tests/regression/test_spring_mass_system.cpp
  tests/unit_tests/constraints/CMakeLists.txt
  tests/unit_tests/constraints/test_calculate_fixed_bc_constraint.cpp
  tests/unit_tests/constraints/test_calculate_prescribed_bc_constraint.cpp
  tests/unit_tests/constraints/test_calculate_revolute_joint_constraint.cpp
  tests/unit_tests/constraints/test_calculate_revolute_joint_force.cpp
  tests/unit_tests/constraints/test_calculate_revolute_joint_output.cpp
  tests/unit_tests/constraints/test_calculate_rigid_joint_constraint.cpp
  tests/unit_tests/constraints/test_calculate_rotation_control_constraint.cpp
  tests/unit_tests/constraints/test_constraint.cpp
  tests/unit_tests/constraints/test_constraint_type.cpp
  tests/unit_tests/constraints/test_constraints.cpp
  tests/unit_tests/dof_management/CMakeLists.txt
  tests/unit_tests/dof_management/test_create_constraint_freedom_table.cpp
  tests/unit_tests/elements/test_elements.cpp
  tests/unit_tests/model/test_model.cpp
  tests/unit_tests/solver/test_compute_number_of_non_zeros_constraints.cpp
  tests/unit_tests/solver/test_populate_sparse_row_ptrs_col_inds_constraints.cpp
Labels: enhancement, code-refactoring

#336 Floating Platform CFD Interface Milestone
  src/interfaces/cfd/floating_platform.hpp
  src/interfaces/cfd/floating_platform_input.hpp
  src/interfaces/cfd/interface.cpp
  src/interfaces/cfd/interface.hpp
  src/interfaces/cfd/interface_input.hpp
  src/interfaces/cfd/mooring_line.hpp
  src/interfaces/cfd/mooring_line_input.hpp
  src/interfaces/cfd/node_data.hpp
  src/viz/vtk_lines.hpp
  tests/regression_tests/interfaces/test_cfd_interface.cpp
Labels: enhancement
