Repository Exawind/openturbine, pull requests merged in 2025-02, with the labels that each got.

#349 Refactor LSFE logic to add derivative of shape functions
  src/math/least_squares_fit.hpp
  tests/unit_tests/math/test_least_squares_fit.cpp
Labels: code-refactoring

#348 Quaternion from tangent and twist
  src/math/quaternion_operations.hpp
  src/math/vector_operations.hpp
  tests/unit_tests/math/test_quaternion_operations.cpp
Labels: enhancement

#346 Revise openturbine documentation
  .github/workflows/correctness-linux.yaml
  .github/workflows/correctness-macos.yaml
  .github/workflows/deploy_docs.yaml
  .github/workflows/formatting.yaml
  CMakeLists.txt
  cmake/FindDoxysphinx.cmake
  cmake/FindSphinx.cmake
  cmake/OpenTurbineOptions.cmake
  docs/CMakeLists.txt
  docs/_config.yml
  docs/_toc.yml
  docs/api_docs.md
  docs/compiling.md
  docs/documentation.md
  docs/doxygen/Doxyfile
  docs/doxygen/mainpage.md
  docs/doxygen/mainpage.txt
  docs/getting_started.md
  docs/input_file.md
  docs/intro.md
  docs/reference.md
  docs/requirements.txt
  docs/sphinx/_static/oturb_logo_v1.jpeg
  docs/sphinx/conf.py
  docs/sphinx/developer/AoS_SoA.pdf
  docs/sphinx/developer/dev_plan.rst
  docs/sphinx/developer/documentation.rst
  docs/sphinx/developer/index.rst
  docs/sphinx/developer/overview.rst
  docs/sphinx/developer/tools.rst
  docs/sphinx/index.rst
  docs/sphinx/spelling_wordlist.txt
  docs/sphinx/theory/flexible_beam.rst
  docs/sphinx/theory/index.rst
  docs/sphinx/theory/nonlinear_spring.rst
  docs/sphinx/theory/rigid_body.rst
  docs/sphinx/user/features.rst
  docs/sphinx/user/user.rst
  docs/sphinx/walkthrough/compiling.rst
  docs/sphinx/walkthrough/index.rst
  docs/tools.md
  docs/tutorials.md
Labels: documentation, ci/cd

#350 Made a few optimizations for running OpenTurbine on GPU.
  src/elements/beams/create_beams.hpp
  src/elements/beams/populate_element_views.hpp
  src/solver/contribute_beams_to_sparse_matrix.hpp
  src/solver/create_sparse_dense_solver.hpp
  src/step/assemble_constraints_matrix.hpp
Labels: code-efficiency

#357 Optimizes System Variable Update for Masses and Springs
  src/elements/masses/masses.hpp
  src/elements/springs/springs.hpp
  src/step/CMakeLists.txt
  src/step/assemble_inertia_matrix_masses.hpp
  src/step/assemble_residual_vector_masses.hpp
  src/step/assemble_residual_vector_springs.hpp
  src/step/assemble_stiffness_matrix_masses.hpp
  src/step/assemble_stiffness_matrix_springs.hpp
  src/step/assemble_system_residual_beams.hpp
  src/step/assemble_system_residual_masses.hpp
  src/step/update_system_variables_masses.hpp
  src/step/update_system_variables_springs.hpp
  src/system/masses/CMakeLists.txt
  src/system/masses/calculate_QP_position.hpp
  src/system/masses/calculate_RR0.hpp
  src/system/masses/calculate_gravity_force.hpp
  src/system/masses/calculate_gyroscopic_matrix.hpp
  src/system/masses/calculate_inertia_stiffness_matrix.hpp
  src/system/masses/calculate_inertial_force.hpp
  src/system/masses/calculate_mass_matrix_components.hpp
  src/system/masses/calculate_quadrature_point_values.hpp
  src/system/masses/copy_to_quadrature_points.hpp
  src/system/masses/rotate_section_matrix.hpp
  src/system/masses/update_node_state.hpp
  src/system/springs/CMakeLists.txt
  src/system/springs/calculate_distance_components.hpp
  src/system/springs/calculate_force_coefficients.hpp
  src/system/springs/calculate_force_vectors.hpp
  src/system/springs/calculate_length.hpp
  src/system/springs/calculate_quadrature_point_values.hpp
  src/system/springs/calculate_stiffness_matrix.hpp
  src/system/springs/update_node_state.hpp
  tests/documentation_tests/floating_platform/floating_platform.cpp
  tests/regression_tests/interfaces/test_cfd_interface.cpp
  tests/regression_tests/regression/test_masses.cpp
  tests/regression_tests/regression/test_springs.cpp
  tests/unit_tests/step/test_assemble_residual_vector_springs.cpp
  tests/unit_tests/step/test_assemble_stiffness_matrix_springs.cpp
  tests/unit_tests/system/masses/CMakeLists.txt
  tests/unit_tests/system/masses/test_calculate.hpp
  tests/unit_tests/system/masses/test_calculate_RR0.cpp
  tests/unit_tests/system/masses/test_calculate_gravity_force.cpp
  tests/unit_tests/system/masses/test_calculate_gyroscopic_matrix.cpp
  tests/unit_tests/system/masses/test_calculate_inertia_stiffness_matrix.cpp
  tests/unit_tests/system/masses/test_calculate_inertial_forces.cpp
  tests/unit_tests/system/masses/test_calculate_mass_matrix_components.cpp
  tests/unit_tests/system/masses/test_rotate_section_matrix.cpp
  tests/unit_tests/system/masses/test_update_node_state.cpp
  tests/unit_tests/system/springs/CMakeLists.txt
  tests/unit_tests/system/springs/test_calculate_distance_components.cpp
  tests/unit_tests/system/springs/test_calculate_force_coefficients.cpp
  tests/unit_tests/system/springs/test_calculate_force_vectors.cpp
  tests/unit_tests/system/springs/test_calculate_length.cpp
  tests/unit_tests/system/springs/test_calculate_stiffness_matrix.cpp
  tests/unit_tests/system/springs/test_update_node_state.cpp
Labels: code-efficiency, code-refactoring
